### ISSUE TITLE
module 'gi' have no attribute 'require version'

### ISSUE THREAD

**Issue by Strit** [arunsivaramanneo/GPU-Viewer#10]
I get this traceback when trying to run gpu-viewer on Arch/Manjaro

```
Traceback (most recent call last):
  File "GPUViewer.py", line 5, in <module>
    from Common import MyGtk, fetchImageFromUrl, setScreenSize
  File "/usr/share/gpu-viewer/Files/Common.py", line 4, in <module>
    gi.require_version("Gtk", "3.0")
AttributeError: module 'gi' has no attribute 'require_version'
```

**Comment by arunsivaramanneo** [comment]
That's weird looks like you don't have pygobject installed, you can install it by sudo pip install pygobject

**Comment by Strit** [comment]
I got pygobject-devel and python2-pygobject2 installed.

**Comment by arunsivaramanneo** [comment]
You are facing the same issue yet ?

**Comment by arunsivaramanneo** [comment]
Can you try running python3 GPUViewer.py, in /usr/share/gpu-viewer/Files, I think the version you have installed doesn't doesn't support Gtk 3.0,

**Comment by arunsivaramanneo** [comment]
Try this sudo pacman -S python-gobject python2-gobject gtk3 ...  as per
http://pygobject.readthedocs.io/en/latest/getting_started.html

**Comment by Strit** [comment]
Thanks. Installing python-gobject worked. :)

**Comment by Strit** [comment]
Got the AUR package done.

Let me know if something is wrong with it.
https://aur.archlinux.org/packages/gpu-viewer/

**Comment by arunsivaramanneo** [comment]
Great ... Thanks a lot :+1: I will check and let you know

**Comment by arunsivaramanneo** [comment]
Hey the package seems to have some issue 
The Upstream URL is wrong.
The last line in package is also faulty:
ln -s "/usr/share/$pkgname/GPUViewer" "$pkgdir/usr/bin/$pkgname"

I guess it should be ln -S "/use/share/$pkgname/GPUViewer" "/usr/bin/$pkgname"
And upstream url seems to be pointing at hearthstone

**Comment by lomaforu** [comment]
apt install gir1.2-gstreamer-1.0
