### ISSUE TITLE
Support for Wayland and EGL?

### ISSUE THREAD

**Issue by Valmar33** [arunsivaramanneo/GPU-Viewer#11]
Including glinfo, eglinfo and es2_info? Might require more tabs. ;)

**Comment by arunsivaramanneo** [comment]
Its on my to do list ... its just  i don't have the right setup for testing the application so the delay. I will definitely have a something on this soon ...

**Comment by arunsivaramanneo** [comment]
I have implemented the EGL part in es2_info in OpenGL Tab itself , As OpenGL ES part is already covered i didn't include it. This is how it looks

![screenshot from 2018-04-15 22-15-26](https://user-images.githubusercontent.com/30646692/38780872-bc016404-40fa-11e8-86c4-a0cf408fe93f.png)

**Comment by arunsivaramanneo** [comment]
es2_info part will be delivered this sunday along with some bug fixes related to vulkan loader 1.1.73, Please do let me know how it goes for you

**Comment by arunsivaramanneo** [comment]
Closing this as es2_info gives most of the information, incase Framebuffer details for eglinfo is required please do comment here.
