### ISSUE TITLE
Enable support for internationalization (i18n)

### ISSUE THREAD

**Issue by fuckyourselfup** [arunsivaramanneo/GPU-Viewer#12]
I suggest add multiple languages support using common internationalization libraries already used in a lot of projects (maybe with gettext).

Once support is added, then community members could submit translations to another languages.

**Comment by arunsivaramanneo** [comment]
I will need to look into it ... Will  See how much i can do .. thanks for the Suggestion

**Comment by fuckyourselfup** [comment]
Mainly to texts that are translatable. Features names are usually in English and those shouldn't be translated.

The following list of texts should be translatable:
* "Available device(s)", "Platform name", "No. of ..." (the tags itself but not their values)
* Each tab name inside big tabs Vulkan, OpenGL.., such as "Device", "Properties", "Extensions".
* List view widget header bar titles, such as "Device properties" and "Value".
* Dropdown filter "Show all..." (but not other filters because are hardware dependent) and "Total (<number>)"; also "Type here to filter...".
* Certain values like "true", "false", "none", "read", "write", "local", "yes", "no", "(n/a)".
* Certain parameters/fixed descriptions that aren't a feature of Vulkan/OpenGL..., such as "Platform Vendor", "Dedicated video memory".
* Buttons
* Full help/about big tab

What shouldn't be translatable:
* Features/properties names specific to the technology (OpenGL, Vulkan, OpenCL...) such as "GL_ARB_vertex_shader_layer" and "fillModeNonSolid".
* The name of the device, numeric values , version numbers, ID strings...

I may forgot something, but this should help you.

**Comment by arunsivaramanneo** [comment]
Thanks, I will need to check on this , Not sure how much effort needs to be put it. Will check and update this thread.

**Comment by arunsivaramanneo** [comment]
Well .. I can only support One Language .. so closing this issue
