### ISSUE TITLE
Add a column "Description" for each item with cryptic names

### ISSUE THREAD

**Issue by fuckyourselfup** [arunsivaramanneo/GPU-Viewer#13]
I propose to add a column "Description" or "Explanation" to add an explanation to non tech savvy users about what is or does the feature/extension/property, specially those with cryptic tags/names.

I've made a mockup as an example how could it be.

![mockup](https://user-images.githubusercontent.com/25434695/43098055-570b0cf2-8e94-11e8-88e0-e8b76170d178.png)

As this program it's a frontend of command line utilities, then it should exist a extensive list of strings' descriptions that match most of the existing features.

**Comment by arunsivaramanneo** [comment]
I really don't think i will be able to implement anything for this ... hence closing the issue
