### ISSUE TITLE
Running on dark-skin KDE - looks derp.

### ISSUE THREAD

**Issue by cybik** [arunsivaramanneo/GPU-Viewer#15]
Short version: I use KDE5's Arc Dark and Obsidian Coast color schemes, along with a GTK Theme for it (breeze dark in my case). GPU-Viewer is kind of unusable with this config.

To wit:
- Without alterations: [looks like this](https://imgur.com/gallery/UXUC4gE)
- With alterations: [starts looking better on my machine](https://imgur.com/a/4TK5Rqc)

**Comment by arunsivaramanneo** [comment]
Thanks a lot for your comment ... This helps .. Will fix the Dark theme issue by next release.. Appreciate for reporting this issue

**Comment by arunsivaramanneo** [comment]
closing this issue now .. the app should work fine with Dark or light themes
