### ISSUE TITLE
Resize window issue

### ISSUE THREAD

**Issue by gnarlin** [arunsivaramanneo/GPU-Viewer#16]
Whole program window moves up and to the left when I attempt to resize the program window.

**Comment by arunsivaramanneo** [comment]
It works perfectly on my machine , Can you please let me know what is your screen resolution ?

**Comment by arunsivaramanneo** [comment]
No update on this .. looks like a false issue

**Comment by PeppoDev** [comment]
Unfortunately this is still an issue, I am using a Fedora 42 and I cant resize it. Also it goes always 100% height with no possibility to change.

Its not the flatpak
version v3.15

Specs:
OS: Fedora Linux 42 (Workstation Edition)KERNEL: 6.15.3-200.fc42.x86_64CPU: AMD Ryzen 7 5700G with Radeon GraphicsGPU: AMD Radeon (radeonsi, renoir, ACO, DRM 3.63, 6.15.3-200.fc42.x86_64)GPU DRIVER: 4.6 Mesa 25.0.7RAM: 48 GB
