### ISSUE TITLE
gpu-viewer : Depends: vulkan-tools but it is not installable

### ISSUE THREAD

**Issue by Cytomax55** [arunsivaramanneo/GPU-Viewer#20]
This was working perfectly prior to my reformat

I just reformatted and installed Kubuntu 18.04 64 bit
I try to install doing the following

sudo add-apt-repository ppa:arunsivaraman/gpuviewer
sudo apt-get update
sudo apt-get install gpu-viewer

I get the following error message

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gpu-viewer : Depends: vulkan-tools but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by arunsivaramanneo** [comment]
have you tried installing vulkan-tools with sudo apt install vulkan-tools...  Please follow this 

Sudo apt remove vulkan-utils (if installed)
sudo apt remove vulkan-tools (if already installed)

now install 
sudo apt install vulkan-tools

let me know if this fixes..

**Comment by arunsivaramanneo** [comment]
Closing the Issue as there are no updates

**Comment by mkroops** [comment]
hi i am facing that use, could you please help me

**Comment by arunsivaramanneo** [comment]
Sorry for the delay, did you install any package through .deb file . Can
you remove the package which is causing the problem and reinstall it
