### ISSUE TITLE
why a dfifferent mesa version to glxinfo?

### ISSUE THREAD

**Issue by splace** [arunsivaramanneo/GPU-Viewer#22]
```
glxinfo | grep Mesa
client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.2
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.2
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.2
```

![Screenshot from 2019-05-04 20-35-58](https://user-images.githubusercontent.com/1234848/57184207-ee6d8d80-6eaf-11e9-8ef6-0d9129eb4dba.png)

clean install Ubuntu 19.04

**Comment by arunsivaramanneo** [comment]
Have you installed the app through flathub ??

**Comment by splace** [comment]
yes, it seems so, ubuntu software just gives you what's available without distinguishing the source.

**Comment by arunsivaramanneo** [comment]
Ok that's the problem, if you have installed it through flathub or snap , they have there own sandbox where they have different version of Mesa drivers installed, that's the reason I am still hesitant to release these on snap or flatpak. I would suggest extract the latest version from here and run the install file and let me know if it works

**Comment by splace** [comment]
thanks, this isn't what i was looking for, seems like this should be documented on flathub, i'll probably put a review/comment about this, if i can.
