### ISSUE TITLE
Automatic detection of dedicated graphics

### ISSUE THREAD

**Issue by LinuxGameGeek** [arunsivaramanneo/GPU-Viewer#23]
Hello,
i am using debian 9 stretch on a optimus laptop with the bumblebee-nvidia primus driver installed. When i run the gpu-viewer tool without primusrun or optirun, it only shows integrated graphics. When i use optirun or primusrun it only shows dedicated graphics. It would be nice to start the gpu-viewer tool ordinary and see both cards.
Thanks!

**Comment by arunsivaramanneo** [comment]
Well that's how bumblebee works, I don't think it's the issue with the Application. Are you seeing the OpenGL or the Vulkan section

**Comment by LinuxGameGeek** [comment]
When installed gpu-viewer through flat pack I saw al sections but bumblebee didn't work. When I installed it through the .Deb package bumblebee works but I think vulkan does not show up.

**Comment by LinuxGameGeek** [comment]
Oh okay. Now I see it works, but it only shows normal opengl.
