### ISSUE TITLE
getVulkanVersion error (another)

### ISSUE THREAD

**Issue by nedludd** [arunsivaramanneo/GPU-Viewer#24]
```
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 708, in radcall
    Devices(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 89, in Devices
    valueRHS[0] = getVulkanVersion(valueRHS[0])
  File "/usr/share/gpu-viewer/Files/Common.py", line 174, in getVulkanVersion
    majorVersion = int(value) >> 22
ValueError: invalid literal for int() with base 10: '                      Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz\n'
```
`vulkaninfo.txt` is here: https://gist.github.com/d6c4d75b0e42bb861ff1101e84855c33

**Comment by nedludd** [comment]
Also the VKD files here:

https://gist.github.com/628dbcfaa3069652a931171d6510ef31

`VKDDeviceinfo1.txt` was empty

**Comment by arunsivaramanneo** [comment]
Thanks ..  I will start looking into it...

**Comment by arunsivaramanneo** [comment]
Can you try the new build and let me know if you are still getting the error

**Comment by parkerlreed** [comment]
Getting this same error from master

[vulkaninfo.txt](https://github.com/arunsivaramanneo/GPU-Viewer/files/3962602/vulkaninfo.txt)

**Comment by arunsivaramanneo** [comment]
Have you tied with the latest master.... This should be fine now... Let me know if still the same issue

**Comment by parkerlreed** [comment]
Oh running it locally was somehow still using the system copy. I'll install the master and check.

**Comment by parkerlreed** [comment]
That is working, thanks

![image](https://user-images.githubusercontent.com/841440/70835185-4bc4a800-1dca-11ea-9912-77042e6a545b.png)

**Comment by arunsivaramanneo** [comment]
Awesome ...Thanks a lot.. i guess i can Mark this issue as resolved
