### ISSUE TITLE
Ubuntu 20.04 Focal Python problem

### ISSUE THREAD

**Issue by unikzforce** [arunsivaramanneo/GPU-Viewer#25]
Thanks for creating such a beauty.
unfortunately focal has deprecated python package ( which here is python2) , and for for installing this package it is a mandatory dependency. Now Ubuntu 20.04 has python 3 installed as a default and if you do `sudo apt  get install python` it will install python 3, not the package `gpu-viewer` needs. can you provide something to mitigate the issue?

**Comment by arunsivaramanneo** [comment]
Thanks for reporting this... I will start looking into it... Will get this resolved soon... I believe this is for the Ubuntu PPA ??

**Comment by unikzforce** [comment]
Yes, I just followed the PPA method.
Thanks a lot.

**Comment by arunsivaramanneo** [comment]
I am having issues with Packaging this as of now.. If you want .. You can clone it and install with the install script.. I will have to move back to 19.10 or 18.04 to get the packaging done.. Will keep this issue posted... Thanks for the support

**Comment by unikzforce** [comment]
Sure, Thanks a Lot for the effort

**Comment by arunsivaramanneo** [comment]
Looks like this is working just fine now.. through PPA.. let me know otherwise
