### ISSUE TITLE
List index out of range error

### ISSUE THREAD

**Issue by qarmin** [arunsivaramanneo/GPU-Viewer#27]
GTX 970 Nvidia  440.100 Ubuntu 20.04

When running program, then out range shows:
```
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 613, in radcall
    MemoryTypes(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 279, in MemoryTypes
    mRhs.append(mRHS[j])
IndexError: list index out of range

```

**Comment by arunsivaramanneo** [comment]
Can you please Share your Vulkaninfo report or let me know the version that's installed

**Comment by qarmin** [comment]
[vulkaninfo.txt](https://github.com/arunsivaramanneo/GPU-Viewer/files/5011790/vulkaninfo.txt)

**Comment by arunsivaramanneo** [comment]
Ok... Well i thought the ubuntu Version 20.04 doesn't have vulkan-tools version more than 1.2.131...Will fix and let you know... Thanks again for the feedback

**Comment by arunsivaramanneo** [comment]
Can you please try this build and let me know if it fixed your issue.

https://github.com/arunsivaramanneo/GPU-Viewer/releases/download/v1.25/gpu-viewer_1.25groovy1-1_amd64.deb

**Comment by qarmin** [comment]
Now shows no error, thanks.

**Comment by arunsivaramanneo** [comment]
Thank you .. I will keep this issue Open for sometime until ubuntu updates the Vulkan-Tools version to 1.2.141 or higher or until i get my vulkan tools repository working correctly. If its up I will share the details here, so that people can install the latest version of vulkan-tools on there machine
