### ISSUE TITLE
Insecure repository.

### ISSUE THREAD

**Issue by Goretantath** [arunsivaramanneo/GPU-Viewer#34]
"The repository 'http://ppa.launchpad.net/arunsivaraman/gpuviewer/ubuntu hirsute Release' does not have a Release file. Updating from such a repository can't be done securely, and is therefore disabled by default."  Please make a release file, thanks in advance!

**Comment by arunsivaramanneo** [comment]
This is now done .. you should be able to add the ppa for hirsute and impish... Apologies for the delay
