### ISSUE TITLE
Reporting incorrect Mesa version

### ISSUE THREAD

**Issue by finesseseth** [arunsivaramanneo/GPU-Viewer#45]
I'm not sure if this is the place to post this issue. This is about the flatpak release and doesn't effect install methods listed here. The flathub (https://flathub.org/apps/details/io.github.arunsivaramanneo.GPUViewer) issues link comes here, so I am sorry if this has nothing to do with you.

GPU-Viewer (flatpak) reports Mesa 21.3.8 even though glxinfo/vulkaninfo/clinfo/es2_info all report version 22.0.2 from the terminal.

It seems the flatpak version has it's own Mesa version bundled which would make reported information possibly confusing/incorrect or just not useful considering the purpose of this software.

**Comment by finesseseth** [comment]
Sorry, same issue I just found https://github.com/arunsivaramanneo/GPU-Viewer/issues/22#issue-440365322. Though nothing seems to have come from that. So I won't self close this yet.

**Comment by arunsivaramanneo** [comment]
Yeah Flatpak has its own Drivers installed... if you need to check the drivers installed on your machine .. i would suggest using the ppa or using the meson build to install .. Flatpak and snap have there own sandbox .. sorry about that

**Comment by finesseseth** [comment]
No need to apologise, I'm using another method. Just thought you'd want to know. I'm completely new to flatpak/snap/appimage (I've been avoiding them till now) and noticed this issue.

I'll close it off in that case.

**Comment by tinywrkb** [comment]
Not a bug, the app shows you the correct version of libs in the environment in which it runs.  

You can file a feature request to add the host's versions of libs, and that's in addition to the currently displayed versions of runtime libs.
But I don't think it's possible to fetch without running flatpak-spawn (`$ flatpak-spawn --host host_command...`), and the Flatpak app will never be shipped with the sandbox hole to allow this. It's not acceptable, as it makes it possible to run any host command.  
So if this feature will be added, and will flatpak-spawn then the user would need to add the relevant permission override manually.

If reading host's versions of graphics libs is important for this app, then file a feature request in [flatpak's issue tracker](https://github.com/flatpak/flatpak/issues) and request exporting graphics libs versions.  
Personally, I don't care. Except the terminal emulator, all my desktop applications are Flatpaks.
