### ISSUE TITLE
GPU-Viewer won't open on openSUSE due to missing 'click' module in Python

### ISSUE THREAD

**Issue by kreaninw** [arunsivaramanneo/GPU-Viewer#46]
After built and installed the app, it won't open with `ModuleNotFoundError: No module named 'click'` error in the terminal.

This can be fixed by installing the click module: `pip install click`.

I am on openSUSE Tumbleweed.

**Comment by arunsivaramanneo** [comment]
Thank you ... so the issue is resolved ?

**Comment by kreaninw** [comment]
> Thank you ... so the issue is resolved ?

Yes, the issue is resolved. I can use the app without any issue.

**Comment by arunsivaramanneo** [comment]
Thanks,  closing the issue

**Comment by arunsivaramanneo** [comment]
Issue resolved
