### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by phodina** [arunsivaramanneo/GPU-Viewer#49]
Hello,

I like this application but there are some aspects of the code which make me little bit concerned.
 
First of all you use `os.system()`. Better alternative is `subprocess.Popen()` is strict super-set of `os.system()`.
 
Also why pack binaries? IMHO there should just be Python code.
 
That brings me to dependencies. They should be clearly stated in meson - e.g. "vulkan-tools".

**Comment by arunsivaramanneo** [comment]
Thank you I will look into this and update it once i get time to work on it.  Well on the Vulkan Tools its upto the user which version they want to use

**Comment by phodina** [comment]
No problem, I just wanted to highlight these potential issues :-)

**Comment by arunsivaramanneo** [comment]
I have started making the changes from os.system to subprocess.Popen, when you get a chance pls do check and let me know if any suggestions

**Comment by phodina** [comment]
Perfect, I'll fetch the commits (starting `7769cb6e029b7e08b72af2b483f3c6a1b361146d`) and check them.

Thanks for focusing your energy on the security!

**Comment by arunsivaramanneo** [comment]
Thank you.. I have also started moving the application to Gtk4. I haven't commited any code for sometime now as i am still working on fixing the issues with Gtk.. You can see my progress in Discussion #52 . If you are testing ubuntu 23.04 , you should be able to install it via PPA

**Comment by arunsivaramanneo** [comment]
Hi , i have updated all the code to use the Subprocess.Popen, when you get a chance please do review and let me know if its ok to close this issue

**Comment by arunsivaramanneo** [comment]
Ok i have moved all the code to subprocess ... closing this issue now
