### ISSUE TITLE
openSUSE install instructions

### ISSUE THREAD

**Issue by RafaelLinux** [arunsivaramanneo/GPU-Viewer#51]
Unfortunately, some packages in openSUSE are not "standard". So the correct sentence for openSUSE to install needed libraries is:
`sudo zypper install clinfo Mesa-demo Mesa-vulkan-device-select libvulkan_intel libvulkan_lvp libvulkan_radeon python3 libvdpau1 vulkan-tools`

"M" in mesa libraries must be in uppercase

Please, change in instructions to install

**Comment by arunsivaramanneo** [comment]
Thank you .. I will update

**Comment by RafaelLinux** [comment]
You are wellcome, thanks to you!!!
