### ISSUE TITLE
gpu-viewer_2.02K4-1_amd64.deb on Debian bookworm/sid refuses to install with apt - "dpkg-deb: error: archive uses unknown compression for member 'control.tar.zst'"

### ISSUE THREAD

**Issue by furquan-lp** [arunsivaramanneo/GPU-Viewer#55]
* GPU-Viewer release version: v2.02
* Distro: Debian GNU/Linux bookworm/sid
* Error: **dpkg-deb: error:** archive '/tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-1_amd
64.deb' uses unknown compression for member 'control.tar.zst', giving up
* Cause: Debian doesn't support zstd for dpkg ([#892664](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664))
* Fix: Rebuilding the .deb package

Full apt output:
```
$ sudo apt install ./gpu-viewer_2.02K4-1_amd64.deb 
[sudo] password for xxxx: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'gpu-viewer' instead of './gpu-viewer_2.02K4-1_amd64.deb'
The following additional packages will be installed:
  clinfo gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data
  orchis-gtk-theme vdpauinfo vulkan-tools
The following NEW packages will be installed:
  clinfo gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data
  gpu-viewer orchis-gtk-theme vdpauinfo vulkan-tools
0 upgraded, 8 newly installed, 0 to remove and 318 not upgraded.
Need to get 4,522 kB/6,717 kB of archives.
After this operation, 27.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /home/xxxx/Downloads/gpu-viewer_2.02K4-1_amd64.deb gpu-viewer amd64 2.02K4-1 [2,195 kB]
Get:2 http://deb.debian.org/debian testing/main amd64 clinfo amd64 3.0.21.02.21-1 [53.8 kB]
Get:3 http://deb.debian.org/debian testing/main amd64 gnome-accessibility-themes all 3.28-2 [2,894 kB]
Get:4 http://deb.debian.org/debian testing/main amd64 gnome-themes-extra-data all 3.28-2 [575 kB]
Get:5 http://deb.debian.org/debian testing/main amd64 gnome-themes-extra amd64 3.28-2 [522 kB]
Get:6 http://deb.debian.org/debian testing/main amd64 vulkan-tools amd64 1.3.231.1+dfsg1-1 [257 kB]
Get:7 http://deb.debian.org/debian testing/main amd64 vdpauinfo amd64 1.5-1 [11.6 kB]
Get:8 http://deb.debian.org/debian testing/main amd64 orchis-gtk-theme all 2022-10-19+ds-1 [209 kB]
Fetched 4,522 kB in 2s (1,973 kB/s)   
Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Selecting previously unselected package clinfo.
(Reading database ... 357938 files and directories currently installed.)
Preparing to unpack .../0-clinfo_3.0.21.02.21-1_amd64.deb ...
Unpacking clinfo (3.0.21.02.21-1) ...
Selecting previously unselected package gnome-accessibility-themes.
Preparing to unpack .../1-gnome-accessibility-themes_3.28-2_all.deb ...
Unpacking gnome-accessibility-themes (3.28-2) ...
Selecting previously unselected package gnome-themes-extra-data.
Preparing to unpack .../2-gnome-themes-extra-data_3.28-2_all.deb ...
Unpacking gnome-themes-extra-data (3.28-2) ...
Selecting previously unselected package gnome-themes-extra:amd64.
Preparing to unpack .../3-gnome-themes-extra_3.28-2_amd64.deb ...
Unpacking gnome-themes-extra:amd64 (3.28-2) ...
Selecting previously unselected package vulkan-tools.
Preparing to unpack .../4-vulkan-tools_1.3.231.1+dfsg1-1_amd64.deb ...
Unpacking vulkan-tools (1.3.231.1+dfsg1-1) ...
Selecting previously unselected package vdpauinfo.
Preparing to unpack .../5-vdpauinfo_1.5-1_amd64.deb ...
Unpacking vdpauinfo (1.5-1) ...
Selecting previously unselected package orchis-gtk-theme.
Preparing to unpack .../6-orchis-gtk-theme_2022-10-19+ds-1_all.deb ...
Unpacking orchis-gtk-theme (2022-10-19+ds-1) ...
dpkg-deb: error: archive '/tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-1_amd
64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-
1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

PS: `zstd` is installed

**Comment by furquan-lp** [comment]
The issue stems from the fact that the .deb contains .zst archives (instead of .xz) and as of Sep 2022, [Debian doesn't support zstd decompression in dpkg](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664).

**Comment by furquan-lp** [comment]
Can be fixed by rebuilding the package on Debian from the original .deb package which creates a new .deb package with .xz archives instead of .zst archives. Installing this rebuilt package worked and the application now works fine.

```
$ dpkg-deb --build --root-owner-group gpu-viewer_2.02K4-1_amd64
dpkg-deb: building package 'gpu-viewer' in 'gpu-viewer_2.02K4-1_amd64.deb'.
$ sudo apt install ./gpu-viewer_2.02K4-1_amd64.deb 
[sudo] password for xxxx: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'gpu-viewer' instead of './gpu-viewer_2.02K4-1_amd64.deb'
The following additional packages will be installed:
  clinfo gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data
  orchis-gtk-theme vdpauinfo vulkan-tools
The following NEW packages will be installed:
  clinfo gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data
  gpu-viewer orchis-gtk-theme vdpauinfo vulkan-tools
0 upgraded, 8 newly installed, 0 to remove and 318 not upgraded.
Need to get 0 B/6,717 kB of archives.
After this operation, 27.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /home/xxxx/Downloads/gpu-viewer_2.02K4-1_amd64.deb gpu-viewer amd64 2.02K4-1 [2,195 kB]
Retrieving bug reports... Done
Parsing Found/Fixed information... Done
Selecting previously unselected package clinfo.
(Reading database ... 357938 files and directories currently installed.)
Preparing to unpack .../0-clinfo_3.0.21.02.21-1_amd64.deb ...
Unpacking clinfo (3.0.21.02.21-1) ...
Selecting previously unselected package gnome-accessibility-themes.
Preparing to unpack .../1-gnome-accessibility-themes_3.28-2_all.deb ...
Unpacking gnome-accessibility-themes (3.28-2) ...
Selecting previously unselected package gnome-themes-extra-data.
Preparing to unpack .../2-gnome-themes-extra-data_3.28-2_all.deb ...
Unpacking gnome-themes-extra-data (3.28-2) ...
Selecting previously unselected package gnome-themes-extra:amd64.
Preparing to unpack .../3-gnome-themes-extra_3.28-2_amd64.deb ...
Unpacking gnome-themes-extra:amd64 (3.28-2) ...
Selecting previously unselected package vulkan-tools.
Preparing to unpack .../4-vulkan-tools_1.3.231.1+dfsg1-1_amd64.deb ...
Unpacking vulkan-tools (1.3.231.1+dfsg1-1) ...
Selecting previously unselected package vdpauinfo.
Preparing to unpack .../5-vdpauinfo_1.5-1_amd64.deb ...
Unpacking vdpauinfo (1.5-1) ...
Selecting previously unselected package orchis-gtk-theme.
Preparing to unpack .../6-orchis-gtk-theme_2022-10-19+ds-1_all.deb ...
Unpacking orchis-gtk-theme (2022-10-19+ds-1) ...
Selecting previously unselected package gpu-viewer.
Preparing to unpack .../7-gpu-viewer_2.02K4-1_amd64.deb ...
Unpacking gpu-viewer (2.02K4-1) ...
Setting up vdpauinfo (1.5-1) ...
Setting up clinfo (3.0.21.02.21-1) ...
Setting up gnome-themes-extra-data (3.28-2) ...
Setting up vulkan-tools (1.3.231.1+dfsg1-1) ...
Setting up gnome-themes-extra:amd64 (3.28-2) ...
Setting up gnome-accessibility-themes (3.28-2) ...
Setting up orchis-gtk-theme (2022-10-19+ds-1) ...
Setting up gpu-viewer (2.02K4-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for bamfdaemon (0.5.6+repack-1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.11.1-1) ...

```

**Comment by arunsivaramanneo** [comment]
thanks for letting me know the issue and fix as well

**Comment by arunsivaramanneo** [comment]
thanks for letting me know the issue and fix as well

**Comment by arunsivaramanneo** [comment]
also, would you be able to post snapshot of the application if you can , need to know how it renders in debian sid.. thanks

**Comment by furquan-lp** [comment]
> also, would you be able to post snapshot of the application if you can , need to know how it renders in debian sid.. thanks

You're welcome, here ya go...
![Snapshot_2022-12-24_14-40-28](https://user-images.githubusercontent.com/22724578/209429023-a322e24b-70da-44f9-bcdd-106ac45ec1b5.png)

**Comment by ZxSix666** [comment]
> * Wersja wydania GPU-Viewer: v2.02
> * Dystrybucja: Debian GNU/Linux bookworm/sid
> * Błąd: **dpkg-deb: błąd:** archiwum „/tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-1_amd 
>   64.deb” używa nieznanej kompresji dla elementu „control.tar.zst”, rezygnując
> * Przyczyna: Debian nie obsługuje zstd dla dpkg ( [#892664](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664) )
> * Poprawka: Odbudowa pakietu .deb
> 
> Pełne trafne wyjście:
> 
> ```
> $ sudo apt install ./gpu-viewer_2.02K4-1_amd64.deb 
> [sudo] password for xxxx: 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'gpu-viewer' instead of './gpu-viewer_2.02K4-1_amd64.deb'
> The following additional packages will be installed:
>   clinfo gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data
>   orchis-gtk-theme vdpauinfo vulkan-tools
> The following NEW packages will be installed:
>   clinfo gnome-accessibility-themes gnome-themes-extra gnome-themes-extra-data
>   gpu-viewer orchis-gtk-theme vdpauinfo vulkan-tools
> 0 upgraded, 8 newly installed, 0 to remove and 318 not upgraded.
> Need to get 4,522 kB/6,717 kB of archives.
> After this operation, 27.3 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 /home/xxxx/Downloads/gpu-viewer_2.02K4-1_amd64.deb gpu-viewer amd64 2.02K4-1 [2,195 kB]
> Get:2 http://deb.debian.org/debian testing/main amd64 clinfo amd64 3.0.21.02.21-1 [53.8 kB]
> Get:3 http://deb.debian.org/debian testing/main amd64 gnome-accessibility-themes all 3.28-2 [2,894 kB]
> Get:4 http://deb.debian.org/debian testing/main amd64 gnome-themes-extra-data all 3.28-2 [575 kB]
> Get:5 http://deb.debian.org/debian testing/main amd64 gnome-themes-extra amd64 3.28-2 [522 kB]
> Get:6 http://deb.debian.org/debian testing/main amd64 vulkan-tools amd64 1.3.231.1+dfsg1-1 [257 kB]
> Get:7 http://deb.debian.org/debian testing/main amd64 vdpauinfo amd64 1.5-1 [11.6 kB]
> Get:8 http://deb.debian.org/debian testing/main amd64 orchis-gtk-theme all 2022-10-19+ds-1 [209 kB]
> Fetched 4,522 kB in 2s (1,973 kB/s)   
> Retrieving bug reports... Done
> Parsing Found/Fixed information... Done
> Selecting previously unselected package clinfo.
> (Reading database ... 357938 files and directories currently installed.)
> Preparing to unpack .../0-clinfo_3.0.21.02.21-1_amd64.deb ...
> Unpacking clinfo (3.0.21.02.21-1) ...
> Selecting previously unselected package gnome-accessibility-themes.
> Preparing to unpack .../1-gnome-accessibility-themes_3.28-2_all.deb ...
> Unpacking gnome-accessibility-themes (3.28-2) ...
> Selecting previously unselected package gnome-themes-extra-data.
> Preparing to unpack .../2-gnome-themes-extra-data_3.28-2_all.deb ...
> Unpacking gnome-themes-extra-data (3.28-2) ...
> Selecting previously unselected package gnome-themes-extra:amd64.
> Preparing to unpack .../3-gnome-themes-extra_3.28-2_amd64.deb ...
> Unpacking gnome-themes-extra:amd64 (3.28-2) ...
> Selecting previously unselected package vulkan-tools.
> Preparing to unpack .../4-vulkan-tools_1.3.231.1+dfsg1-1_amd64.deb ...
> Unpacking vulkan-tools (1.3.231.1+dfsg1-1) ...
> Selecting previously unselected package vdpauinfo.
> Preparing to unpack .../5-vdpauinfo_1.5-1_amd64.deb ...
> Unpacking vdpauinfo (1.5-1) ...
> Selecting previously unselected package orchis-gtk-theme.
> Preparing to unpack .../6-orchis-gtk-theme_2022-10-19+ds-1_all.deb ...
> Unpacking orchis-gtk-theme (2022-10-19+ds-1) ...
> dpkg-deb: error: archive '/tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-1_amd
> 64.deb' uses unknown compression for member 'control.tar.zst', giving up
> dpkg: error processing archive /tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-
> 1_amd64.deb (--unpack):
>  dpkg-deb --control subprocess returned error exit status 2
> Errors were encountered while processing:
>  /tmp/apt-dpkg-install-42hwNa/7-gpu-viewer_2.02K4-1_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```
> 
> PS: `zstd`jest zainstalowany

**Comment by ZxSix666** [comment]
a

**Comment by Danny3** [comment]
Since Debian Bookworm fixed the support for Zstd and similar problems that I had with other programs being gone...
Isn't this fixed too so the issue can be closed?
