### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Strit** [arunsivaramanneo/GPU-Viewer#57]
A user of the AUR package mentioned that he/she only gets a white window when running GPU Viewer.

The output from CLI is:

```
~ : gpu-viewer 
/bin/sh: line 1: xdpyinfo: comandă negăsită Traceback (most recent call last): File "/usr/share/gpu-viewer/Files/GPUViewer.py", line 144, in on_activate width,height = getScreenSize() File "/usr/share/gpu-viewer/Files/Common.py", line 43, in getScreenSize return screen_resolution[0].strip('\n'),screen_resolution[1].strip('\n') IndexError: list index out of range 
```

Am I missing a dependency on `xorg-xdpyinfo` or is this some other issue?
I couldn't see any xdpyinfo related code in GPUViewer.py or Common.py, but I did find it in [Filenames.py](https://github.com/arunsivaramanneo/GPU-Viewer/blob/master/Files/Filenames.py#L9), so a missing dependency is likely the issue, but wanted to confirm.
If it is required, then the meson build system should notify me. :smile:

**Comment by arunsivaramanneo** [comment]
yes, xdyinfo has to be added as dependency. sorry completely forgot to mention that

**Comment by Strit** [comment]
Okay, thanks. Updated the AUR package to include that.

**Comment by arunsivaramanneo** [comment]
thanks ... yes i too didn't encountered this issue in ubuntu or manjaro KDE , thought they are already installed by default , but this program is for only x11 system, so  anyone purely using a wayland system may encounter this issue. i will have to find another way to get the screen resolution and remove xdyinfo

**Comment by Strit** [comment]
My system is wayland and I didn't encounter it, because xorg-xdpyinfo was installed as a dependency for kinfocenter (a KDE appliaction). So I added it as a dependency to the gpu-viewer AUR package so that should fix it for the people that was not so lucky.

My point was that it's a dependency and meson as a compiler should check for each dependency and notify users/compilers which are missing, if any. It does this, if dependencies are defined in the meson.build file.

**Comment by arunsivaramanneo** [comment]
Thanks .. Got your point .. there were no dependencies added to the meson.build , I will try to update it to include all the dependencies..

**Comment by ferdnyc** [comment]
@arunsivaramanneo You're using Gtk4 for the UI, right? In Python using gi? You can query screen dimensions like this:
```python3
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, Gdk

display = Gtk.Display.get_default()
monitors = display.list_monitors()
for m in monitors:
    g = m.get_geometry()
    print(f"This screen's dimensions are {g.width}×{g.height})
    print(f"It's located at {g.x},{g.y} in the virtual screen area")
```

**Comment by ferdnyc** [comment]
(And now that I've closed the quotes on my f-string, it'll even work.)

**Comment by ferdnyc** [comment]
Note, also, that the geometry returned is in scaled pixels. If the system has a HiDPI display, you'd need to multiply by `m.get_scale_factor().width` and `m.get_scale_factor().height`to get the true hardware pixel dimensions. (If that matters, which it probably doesn't because if you're setting things like window dimensions, scaled pixels are the units you want to work in anyway.)

**Comment by arunsivaramanneo** [comment]
Thanks I will take a look tomorrow ... Thamk you so much ..

**Comment by arunsivaramanneo** [comment]
> @arunsivaramanneo You're using Gtk4 for the UI, right? In Python using gi? You can query screen dimensions like this:
> 
> ```python
> import gi
> gi.require_version('Gtk', '4.0')
> from gi.repository import Gtk, Gdk
> 
> display = Gdk.Display.get_default()
> monitors = display.get_monitors()
> for m in monitors:
>     g = m.get_geometry()
>     print(f"This screen's dimensions are {g.width}×{g.height}")
>     print(f"It's located at {g.x},{g.y} in the virtual screen area")
> ```

@ferdnyc thanks a lot i have just pushed a commit with the changes you have mentioned. it works fine on my machine i will do more testing (multi monitor setup) and see if all looks ok
