### ISSUE TITLE
[Flatpak] Failed to open VDPAU backend libvdpau_nouveau.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Fabxx** [arunsivaramanneo/GPU-Viewer#64]
[log.txt](https://github.com/arunsivaramanneo/GPU-Viewer/files/10518675/log.txt)

tested on a fresh Arch Linux install with all open source drivers installed by default.
The nvidia GPU is not detected, only intel iGPU and LLVM

**Comment by tinywrkb** [comment]
The joy of using Nvidia's binary ****.  
You need to confirm that you have the same version of Nvidia driver in the host system and Flatpak.  
When you update Flatpak, it should pick up the host system driver version and install the same for the Flatpak runtimes. That's of course if the driver version is available on Flathub.

System driver version
```
$ pacman -Qi nvidia
```

Flatpak driver version
```
$ flatpak list --runtime | grep org.freedesktop.Platform.GL.nvidia | grep 22.08
```
or
```
$ flatpak info --system --show-extensions  org.gnome.Platform//43
```

**Comment by Fabxx** [comment]
doing flatpak update with the name package resolved the issue, thank you for pointing this out
