### ISSUE TITLE
gi.require_version('Gtk','4.0')

### ISSUE THREAD

**Issue by windlepoons** [arunsivaramanneo/GPU-Viewer#71]
When I try starting gpu-viewer in the terminal, it shows following output:
```
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/GPUViewer.py", line 5, in <module>
    import Common
  File "/usr/share/gpu-viewer/Files/Common.py", line 7, in <module>
    gi.require_version('Gtk','4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
```
I have installed the following packages:
GTK 3: libgtk-3-0, libgtk-3-bin, libgtk-3-common, libgtk-3-dev
GTK 4: libgtk-4-1, libgtk-4-bin und libgtk-4-common but not libgtk-4-dev because not needed yet.
With libgtk-4-dev installed, gpu-viewer starts without problems.

If gpu-viewer has a dependency on libgtk-4-dev, that should be added to the control file.
Currently in the control file in the *.deb package:
`Depends: python3-gi, python3-gi-cairo, clinfo, vulkan-tools, mesa-utils, mesa-utils-extra, vdpauinfo, libgtk-4-1`

gpu-viewer version: 2.26
OS: Siduction/Xfce (Debian/sid)

**Comment by arunsivaramanneo** [comment]
Thanks for raising it .. i thought i had added the libgtk-4-dev as dependency. i will add that in my next release. Will leave this issue open till the next Release

**Comment by arunsivaramanneo** [comment]
Hi , I have released a new version and have also added the .deb package to the Release. libgtk-4-dev is now added as dependency . If you can check and confirm if all Ok, please close the issue

**Comment by windlepoons** [comment]
Hi, the version 2.28 install now with libgtk-4-dev (apt install ./gpu-viewer_2.28K2-1_amd64.deb).

**Comment by arunsivaramanneo** [comment]
> Hi, the version 2.28 install now with libgtk-4-dev (apt install ./gpu-viewer_2.28K2-1_amd64.deb). I do not see any way to close my issue.

thanks .. i will close the issue now
