### ISSUE TITLE
GNOME 43 is outdated as dependency in Flatpak version

### ISSUE THREAD

**Issue by edmundlaugasson** [arunsivaramanneo/GPU-Viewer#72]
Output when installed few minutes ago:
```
flatpak install io.github.arunsivaramanneo.GPUViewer

 1. [✓] org.gnome.Platform.Locale                       43                i            flathub            20,5 kB / 340,6 MB
 2. [✓] org.gnome.Platform                              43                i            flathub           194,0 MB / 329,3 MB
 3. [✓] io.github.arunsivaramanneo.GPUViewer            stable            i            flathub            12,8 MB / 9,0 MB
```
But already in [March 2023 (3 months ago) is GNOME 44 out](https://release.gnome.org/). Please update!

**Comment by arunsivaramanneo** [comment]
Thanks for raising this, i am trying to check if anyone from Flathub team can help merge the commits , once i have an update will post it here

**Comment by IlgazC** [comment]
In addition the new Flathub portal shows a rather serious message to users.
![Screenshot 2023-09-21 at 13-43-48 GPU-Viewer Flathub](https://github.com/arunsivaramanneo/GPU-Viewer/assets/19528613/c9900d21-ca2a-4b47-8135-2f6e1d587765)

**Comment by pedrolcl** [comment]
This is what the command line flatpak utility says today:

$ flatpak update
...
Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.arunsivaramanneo.GPUViewer

**Comment by arunsivaramanneo** [comment]
I have reached out to the Flatpak team for the last few Release to update it .. but they seem to be busy, I will try to see if anyone can help

https://github.com/flathub/io.github.arunsivaramanneo.GPUViewer/pull/67

**Comment by arunsivaramanneo** [comment]
> In addition the new Flathub portal shows a rather serious message to users. ![Screenshot 2023-09-21 at 13-43-48 GPU-Viewer Flathub](https://user-images.githubusercontent.com/19528613/269584997-c9900d21-ca2a-4b47-8135-2f6e1d587765.png)

I am really not sure why its coming as Legacy Windowing System, my application only shows what is the Windowing System being used by the machine

**Comment by arunsivaramanneo** [comment]
looks like they have merged the pull request, hope it works Ok now

**Comment by arunsivaramanneo** [comment]
Yeah i can see the application is finally updated to version 2.29 in flathub.. Hope this can be closed now
