### ISSUE TITLE
[flatpak] opencl information incomplete

### ISSUE THREAD

**Issue by IlgazC** [arunsivaramanneo/GPU-Viewer#73]
I am using digikam's opencl features for managing massive amount of photos so I wanted to validate opencl. After installing intel's opencl support to openSUSE Tumbleweed and clinfo , I get this result:
[clinfo.txt](https://github.com/arunsivaramanneo/GPU-Viewer/files/12642448/clinfo.txt)

However, GPU Viewer shows just this:
![gpu_viewer_opencl](https://github.com/arunsivaramanneo/GPU-Viewer/assets/19528613/15b89186-f19c-43ac-98e2-168a83fed660)

clinfo looks like it is in a standard location
>which clinfo
/usr/bin/clinfo

> clinfo --version
clinfo version 3.0.23.01.25

**Comment by arunsivaramanneo** [comment]
Thanks for raising this issue .. I am not finding time to update the application for some time now due to my Work.. as soon as i have time i will look into it .. sorry for the delay in responding

**Comment by arunsivaramanneo** [comment]
Well i did take a look , seems like Clover doesn't support all the devlices (and its been ages clover had a proper update) , so what you are seeing seems to be expected it just i didn't know that i will end up in this scenario where platform details are present but not the device details. Seems like the new RustIcl from Mesa also only has platform details no device details as on this date.  POCL should work just fine (if i am not wrong)
