### ISSUE TITLE
libadwaita

### ISSUE THREAD

**Issue by gmankab** [arunsivaramanneo/GPU-Viewer#75]
switch to libadwaita design please

**Comment by arunsivaramanneo** [comment]
i'm still trying to figure out Gtk4 , finally i just started moving from TreeView to ColumnView. i will try to get some libadwaita done

**Comment by gmankab** [comment]
thank you, waiting for a release to test it

**Comment by arunsivaramanneo** [comment]
Are you using Ubuntu 23.10 or other distros

**Comment by gmankab** [comment]
i use fedora silverblue and flatpaked gpu-viewer

i can run build for ubuntu in distrobox
