### ISSUE TITLE
Missing images => No Vulkan info

### ISSUE THREAD

**Issue by leafi** [arunsivaramanneo/GPU-Viewer#76]
Hi,

Just upgraded to 3.0 courtesy of the updated AUR package.

Alas, on my hardware, there is no longer any Vulkan info - the lists are empty, despite a device being selected. Other tabs are fine. Running gpu-viewer from the terminal yields the following output:

```
(python3:46540): Gtk-CRITICAL **: 18:15:42.921: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 1183, in radcall
    Devices(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 198, in Devices
    cpu_logo = getLogo(valueRHS[i])
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 337, in getLogo
    logo_pixbuf = fetchImageFromUrl(const.Ryzen_logo,32,28, True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 61, in fetchImageFromUrl
    return GdkPixbuf.Pixbuf.new_from_file_at_scale(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “../Images/Ryzen_Dark.svg”: No such file or directory (4)
2.150301218032837
```

Basically, there is no file Images/Ryzen_Dark.svg, and when an image fails to load, it seems the Vulkan tab fails to populate, too.

When I copy Images/Ryzen.svg to Images/Ryzen_Dark.svg, it takes notably longer to start gpu-viewer than before but then the Vulkan tab is actually populated & works.

I had a look through Files/const.py. The following entries are declared but their paths do not exist:

- DUMMY_PIXBUF, 8e8e8e.png
- TWITTER_LOGO_PNG, twitter-icon.png
- NVIDIA_BANNER, nvidia-banner.jpg
- INTEL_BANNER, Intel_Banner.png
- MESA_LOGO_PNG, mesa-logo.png
- AMD_Ryzen_RADEON_LOGO_PNG, AMD_Ryzen_Radeon.png
- AMD_RADEON_VEGA_LOGO_PNG, radeon-vega.jpg
- Linux_Lite_logo, Linux-Lite-Logo.png
- Steam_OS_logo, Steam_icon_logo.png
- Intel_core_i7_logo, intel-logo-core-i7.png
- Ryzen_logo, Ryzen_Dark.svg

However, of the above, only these constants are actually used in gpu-viewer's code:

- MESA_LOGO_PNG
- Ryzen_logo

It might be worth structuring the Images directory differently in the future: when you have e.g. nvidia-logo.png, nvidia_logo.png and Nvidia_logo.png in the same directory, and only some of the present images are used, some are unused, and const.py has some entries never used in the app, which point to files that may or may not exist, and both variables and files have random unrelated casing, it's extremely easy for bugs to sneak in.

In any case, thanks for working on GPU-Viewer. I've found it useful.

**Comment by arunsivaramanneo** [comment]
I have pushed a new Release , AUR should be updated shortly. Please let me know if it fixes the issue and can be closed
