### ISSUE TITLE
Vulkan info is not displayed

### ISSUE THREAD

**Issue by archiebug** [arunsivaramanneo/GPU-Viewer#82]
Hi-

Thanks for the great app!

With the latest update, the Vulkan tab no longer displays anything.  When I launch the app from the terminal, i get the following exceptions.  It seems to be the second awk command.

```
/usr/share/gpu-viewer/Files/VulkanViewer.py:106: SyntaxWarning: invalid escape sequence '\('
  fetch_vulkan_gpu_info_command = "vulkaninfo --summary | awk '/GPU%d/{flag=1;next}/^GPU.*/{flag=0}flag' | awk '{gsub(/\([0-9].*/,'True');}1' | sort " %(GPUname)
/usr/share/gpu-viewer/Files/VulkanViewer.py:693: SyntaxWarning: invalid escape sequence '\('
  fetch_vulkan_device_memory_heaps_rhs_command = "cat %s | grep = | grep -v count| grep -o  =.* | grep -o ' .*' | awk '{gsub(/\(.*/,'True');print}' " %(Filenames.vulkan_device_memory_heaps_file)
/usr/share/gpu-viewer/Files/VulkanViewer.py:855: SyntaxWarning: invalid escape sequence '\('
  fetch_vulkan_device_layer_names_command = "cat %s | grep _LAYER_ | awk '{gsub(/\(.*/,'True');print} '" %(Filenames.vulkan_device_layers_file)
/usr/share/gpu-viewer/Files/VulkanViewer.py:858: SyntaxWarning: invalid escape sequence '\('
  fetch_vulkan_device_layer_description_command = "cat %s | grep _LAYER_ | grep -o \(.* | awk '{gsub(/\).*/,'True');print}'| awk '{gsub(/\(/,'True');print}' " %(Filenames.vulkan_device_layers_file)
```

![Screenshot from 2024-10-05 12-57-44](https://github.com/user-attachments/assets/cf8b87b8-0fef-404a-92ef-086187aea093)

This exception also appears and seems to be a separate issue. 

```
(python3:20503): Gtk-CRITICAL **: 12:54:09.793: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 1183, in radcall
    Devices(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 198, in Devices
    cpu_logo = getLogo(valueRHS[i])
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 306, in getLogo
    logo_pixbuf = fetchImageFromUrl(const.Ryzen_logo,32,28, True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 61, in fetchImageFromUrl
    return GdkPixbuf.Pixbuf.new_from_file_at_scale(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “../Images/Ryzen_Dark.svg” (3)
```

**Comment by arunsivaramanneo** [comment]
Hi .. Is this via flathub or AUR ?

**Comment by archiebug** [comment]
Hi-

AUR.

-------- Original Message --------

**Comment by arunsivaramanneo** [comment]
Is it not displaying even the first tab  ? or is it the extension tab ... I can see its all Syntax warning which is Ok and should not crash the App .. 

if you can provide me the vulkaninfo output that would be great pls

**Comment by archiebug** [comment]
Hi-
Nothing shows up on the Vulkan tab.  Here is the output of vulkaninfo:

[vkinfo.out.txt](https://github.com/user-attachments/files/17267680/vkinfo.out.txt)

**Comment by arunsivaramanneo** [comment]
Thanks for the vkinfo file , i have tested that file in my machine and it works Ok .. I suspect the Ryzen logo is not loading for you ...thats why its failing ... i too have a Ryzen machine and it works just fine for me.  I will see if i can change the logo from .svg to .png

**Comment by edt-xx** [comment]
Just so you know.  This is happening for more than on person:

```
XDG_RUNTIME_DIR=/run/user/1000 gpu-viewer
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/libvulkan_virtio.so. Skipping this driver.

(python3:781317): Gtk-CRITICAL **: 09:56:34.233: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/libvulkan_virtio.so. Skipping this driver.
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 1184, in radcall
    Devices(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 198, in Devices
    cpu_logo = getLogo(valueRHS[i])
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 306, in getLogo
    logo_pixbuf = fetchImageFromUrl(const.Ryzen_logo,32,28, True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 61, in fetchImageFromUrl
    return GdkPixbuf.Pixbuf.new_from_file_at_scale(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “../Images/Ryzen_Dark.svg” (3)
2.1491506099700928
```

This was built from AUR Dec 1 on an up to date Arch install.  Also 
```
env | grep XDG_RUNTIME_DIR
XDG_RUNTIME_DIR=/run/user/1000
```
but without it is not found unless I set it in the the commandline.

Thanks

**Comment by arunsivaramanneo** [comment]
@edt-xx  Can you try clone and installing the application, I have updated the Ryzen logo .. if its fixed i will update the Release

**Comment by archiebug** [comment]
Thanks for the update.  I still have the same issues as above.  Here are some error outputs:

`(python3:106298): Gtk-CRITICAL **: 20:37:07.627: gtk_box_append: assertion 'gtk_widget_get_parent (child) == NULL' failed
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 1184, in radcall
    Devices(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 198, in Devices
    cpu_logo = getLogo(valueRHS[i])
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 306, in getLogo
    logo_pixbuf = fetchImageFromUrl(const.Ryzen_logo,32,28, True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpu-viewer/Files/Common.py", line 61, in fetchImageFromUrl
    return GdkPixbuf.Pixbuf.new_from_file_at_scale(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “../Images/Ryzen_Dark.svg” (3)
0.36589860916137695
`

`/usr/share/gpu-viewer/Files/OpenCL.py:47: SyntaxWarning: invalid escape sequence '\('
  oclPlatformslocal[i] = [j.replace("(", "\(") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:48: SyntaxWarning: invalid escape sequence '\)'
  oclPlatformslocal[i] = [j.replace(")", "\)") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:72: SyntaxWarning: invalid escape sequence '\('
  oclPlatformslocal[i] = [j.replace("(", "\(") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:73: SyntaxWarning: invalid escape sequence '\)'
  oclPlatformslocal[i] = [j.replace(")", "\)") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:108: SyntaxWarning: invalid escape sequence '\('
  oclPlatformslocal[i] = [j.replace("(", "\(") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:109: SyntaxWarning: invalid escape sequence '\)'
  oclPlatformslocal[i] = [j.replace(")", "\)") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:113: SyntaxWarning: invalid escape sequence '\/'
  fetch_device_details_file_command = "cat %s | awk '/%s/&& ++n == 2,/%s*/' | awk '/Device Name.*/&& ++n == %d,/Preferred \/.*/' | grep -v Preferred | grep -v Available" % (Filenames.opencl_output_file,oclPlatformslocal[value2], oclPlatformslocal[value2 + 1], value + 1)
/usr/share/gpu-viewer/Files/OpenCL.py:190: SyntaxWarning: invalid escape sequence '\('
  oclPlatformslocal[i] = [j.replace("(", "\(") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:191: SyntaxWarning: invalid escape sequence '\)'
  oclPlatformslocal[i] = [j.replace(")", "\)") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:244: SyntaxWarning: invalid escape sequence '\('
  oclPlatformslocal[i] = [j.replace("(", "\(") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:245: SyntaxWarning: invalid escape sequence '\)'
  oclPlatformslocal[i] = [j.replace(")", "\)") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:248: SyntaxWarning: invalid escape sequence '\/'
  fetch_device_vector_details_file_command = "cat %s | awk '/%s/&& ++n == 2,/%s/' | awk '/Device Name.*/&& ++n == %d,/Extensions.*/'| awk '/Preferred \/.*/{flag=1;print}/Address.*/{flag=0}flag' | uniq" % (Filenames.opencl_output_file, oclPlatformslocal[value2], oclPlatformslocal[value2 + 1], value + 1)
/usr/share/gpu-viewer/Files/OpenCL.py:298: SyntaxWarning: invalid escape sequence '\('
  oclPlatformslocal[i] = [j.replace("(", "\(") for j in oclPlatformslocal[i]]
/usr/share/gpu-viewer/Files/OpenCL.py:299: SyntaxWarning: invalid escape sequence '\)'
  oclPlatformslocal[i] = [j.replace(")", "\)") for j in oclPlatformslocal[i]]
`

I did a fresh build from AUR and it complied without issue.  Let me know if you need anymore info.

**Comment by arunsivaramanneo** [comment]
@archiebug  Sorry is this the one tested with latest commit ? or is it still the one updated in Arch .. I have pushed a fix but haven't release that fix .. want someone to test that and see if it works before pushing it out for a Release

**Comment by archiebug** [comment]
https://aur.archlinux.org/packages/gpu-viewer

Looks like v3.08 is what I upgraded to.

**Comment by archiebug** [comment]
> @archiebug @edt-xx i have updated the app again .. when you get time and when the AUR is updated .. please do check and let me know .. thank you

Did a fresh pull and compile on v3.10.  It works now.  Thank you for the fix!

![Screenshot from 2024-12-03 19-57-45](https://github.com/user-attachments/assets/801708f2-292e-476b-aea4-d1859462d013)

**Comment by arunsivaramanneo** [comment]
Thank you for the update I will close the incident now
